version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 200000
    ports:
        - 22181:2181
    healthcheck:
      test: "nc -z localhost 2181"
      interval: 5s
      timeout: 1s
      retries: 10

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - 29092:9092
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: "nc -z localhost 9092"
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



  producer:
    image: kafka-producer
    depends_on:
      - kafka
    ports:
      - 8080:8080
    healthcheck:
      test: "nc -z localhost 8080"
      interval: 10s
      timeout: 10s
      retries: 10

  consumer:
    image: kafka-consumer
    depends_on:
      - kafka
    ports:
      - 8081:8081
    healthcheck:
      test: "nc -z localhost 8081"
      interval: 10s
      timeout: 10s
      retries: 10
