version: '1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181
    healthcheck:
      test: "nc -z 127.0.0.1 2181"
      interval: 5s
      timeout: 1s
      retries: 10

  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - 9092
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: "/opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper --list | grep data.quote.stream.${PRODUCT_TYPE}.event.time"
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "data.quote.stream.${PRODUCT_TYPE}.event.time:12:1,data.quote.stream.${PRODUCT_TYPE}.joined-events:12:1,data.quote.stream.${PRODUCT_TYPE}.joined-events.deser-dlq:12:1,data.quote.stream.${PRODUCT_TYPE}.joined-events.processing-dlq:12:1,raw:12:1,data.quote.stream.joined-events.deser-dlq:12:1,data.quote.stream.joined-events.dlq:12:1"
