server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      client: client
      transaction: transaction
    template:
      default-topic: raw
